name: af_$(SourceBranchName)_$(Build.SourceVersion)

pool:
  vmImage: 'ubuntu-22.04'

steps:
- script: |
    aws ec2 start-instances --instance-ids $(AWS_INSTANCE_ID)
    aws ec2 wait instance-status-ok --instance-ids $(AWS_INSTANCE_ID)
  displayName: 'Starting up instances in dev'
  env:
    AWS_ACCOUNT_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_ACCOUNT_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AWS_EC2_INSTANCE_ID: $(AWS_INSTANCE_ID)
    AWS_EC2_REGION: $(AWS_REGION)
